version: '3.4'
services:
  tws:
    build: ./ib-gateway-docker-aws
    #image: dvasdekis/ib-gateway-docker:v978
    volumes:
      - ./ib-gateway-docker-gcp/ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib-gateway-docker-gcp/ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TRADING_MODE=${TWS_TRADING_MODE}
      - TWSUSERID=${TWS_USER_ID}
      - TWSPASSWORD=${TWS_PASSWORD}
      - FIXUSERID=
      - FIXPASSWORD=
      - XVFB_ARGS=${XVFB_ARGS}
    restart: always
    ports:
      - 4002:4004
      - 5901:5900
  worker:
    build: ./data-retrieval
    environment:
      - DATABASE_URL=${DATABASE_URL}
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: 'redis:6-alpine'
    ports:
      - 6379:6379


  
